### ISSUE TITLE
Missing resistor

### ISSUE THREAD

**Issue by jmatyas** [sinara-hw/Fast_Servo#10]
![image](https://user-images.githubusercontent.com/48015058/95773549-f776a700-0cbe-11eb-8c08-d92350626d04.png)

According to LTC2195 datasheet (p.23) SDO line should be equipped with an external 2k pull-up resistor in serial programming mode. 
Was leaving it out intentional or perhaps am I missing it somewhere?

**Comment by zdun8** [comment]
It's a mistake. I will fix it. Thank you!

What's interesting NIST servo didn't have the resistor on their board with the ADC, probably it's placed on the motherboard.
