### ISSUE TITLE
PCB issues

### ISSUE THREAD

**Issue by gkasprow** [sinara-hw/Fast_Servo#12]
@zdun8 please look at this
![obraz](https://user-images.githubusercontent.com/4325054/99980416-8095f900-2da8-11eb-8572-1f1e24455f4e.png)

**Comment by zdun8** [comment]
These pins are shorted internally in the ADC. 
![image](https://user-images.githubusercontent.com/5497039/100005731-b697a500-2dc9-11eb-95db-8580cdeb8a63.png)


https://www.analog.com/media/en/technical-documentation/data-sheets/219543f.pdf

**Comment by gkasprow** [comment]
so make them in such way that do not generate DRC errors.

**Comment by zdun8** [comment]
It is not generating DRC.
