### ISSUE TITLE
JTAG connector

### ISSUE THREAD

**Issue by gkasprow** [sinara-hw/Fast_Servo#13]
It's worth considering RA JTAG connector. Access to this one could be difficult due to mezzanine
![obraz](https://user-images.githubusercontent.com/4325054/99980617-b804a580-2da8-11eb-857e-efe640165327.png)
We can leave it for next release

**Comment by zdun8** [comment]
Good point. 

There was a keepout region in Stabilizer on the top and bottom border of the PCB so I have assumed the boards will be placed in some kind of rails, which would make access to right angle connector impossible.
