### ISSUE TITLE
[sch review] wrong supply voltage IC1

### ISSUE THREAD

**Issue by filipswit** [sinara-hw/Fast_Servo#15]
Input voltage should be 5V insted of 3.3V

**Comment by zdun8** [comment]
You are right. We don't have 5.0V supply on the board apart from the analog one. I suggest to use 5.5 V supply and a diode to comply with USB requirements. 
![image](https://user-images.githubusercontent.com/5497039/102711693-e304eb00-42bb-11eb-9513-4d4c124bb360.png)

**Comment by filipswit** [comment]
Looks fine.

**Comment by gkasprow** [comment]
BAS416 is 200mA diode. Replaced it with 1A one
