### ISSUE TITLE
[sch review] C22 connections

### ISSUE THREAD

**Issue by filipswit** [sinara-hw/Fast_Servo#17]
In current configuration pins 2, 4, 6, 8 and 1, 3, 5, 7 are tied together. ~~I think you should rename net labels for 5, 6, 7, 8.~~

![2020-12-12_15h58_58](https://user-images.githubusercontent.com/24258965/101987240-24314580-3c93-11eb-9ee3-bfbed733376a.png)
![2020-12-12_15h59_21](https://user-images.githubusercontent.com/24258965/101987244-27c4cc80-3c93-11eb-90cc-8b7294e766d3.png)

edit:
According to #12, it is in recommended design, but It still shows unconnected nets. My proposition is to add under dash suffix to eliminate it.

![image](https://user-images.githubusercontent.com/24258965/102020708-2ff83700-3d7b-11eb-8867-e11cd56bfb0b.png)

**Comment by filipswit** [comment]
According to #12, it is in recommended design, but It still shows unconnected nets. My proposition is to add under dash suffix to eliminate it.

![image](https://user-images.githubusercontent.com/24258965/102020708-2ff83700-3d7b-11eb-8867-e11cd56bfb0b.png)

**Comment by zdun8** [comment]
Electrically it's still the same net as they are shorted internally in the ADC, so it would be a confusing. I will add a note. 
I've added a rule to not generate DRC for this signals not being connected, but I don't know if there is a way not to show the unconnected nets in the PCB. 

I will change the schematics as follows so it will not generate DRC and will still be clear. 
![image](https://user-images.githubusercontent.com/5497039/102722215-f043c900-42ff-11eb-8244-d702c9bde821.png)
