### ISSUE TITLE
[sch review] U9 wrong configuration of RT and FB

### ISSUE THREAD

**Issue by filipswit** [sinara-hw/Fast_Servo#19]
I don't understand why there is positive converter used to make negative voltage. But in these situation we should treat N5V5 as ground, so FB and RT should be referenced to N5V5 instead of GND.

**Comment by zdun8** [comment]
There is no problem with using this DC/DC converter to generate a negative voltage. It's very small and provides high output current. 

You are right regarding FB and RT, I will correct it, thank you.
