### ISSUE TITLE
DAC IC selection

### ISSUE THREAD

**Issue by zdun8** [sinara-hw/Fast_Servo#2]
The goal of this issue is to discuss the selection of the DAC IC. 

The requirements for DAC channel are as follows:
-DAC channel shall have latency + BW suitable for 3MHz closed-loop applications (including latency of loop filter on FPGA)
-DAC channel shall have fixed +-1V input/output range
-DAC channel bandwidth shall be 100 MHz or 125MHz 
-DAC channel shall have 14 bit ENOB

One option is to use LTC2000, which is used in Shuttler project, but it's quite expensive. 
I have listed a similar ones in this spreadsheet: https://docs.google.com/spreadsheets/d/1j0nTGpnnnBx4UXwtZlGYXvdnvVj7PuF5h2WQjEc7hA4/edit?usp=sharing

Feel free to update the spreadsheet.

**Comment by gkasprow** [comment]
In case of DACs, please also look at the tempco

**Comment by hartytp** [comment]
And again latency will be key...

**Comment by gkasprow** [comment]
@hartytp is it critical for your applications to have dual-channel, well-matched DAC?

**Comment by hartytp** [comment]
> @hartytp is it critical for your applications to have dual-channel, well-matched DAC?

It's always nice to have matching, but that's an extremely weak preference that can/should be overridden by other factors (e.g. cost/performance/simplicity).

The main case where I'd want matched DACs would be IQ mixers etc, but for that I think we should make a separate SDR design with AC-coupled RF AFE. In any case, Phaser solves all our RF DAC needs for now.

**Comment by gkasprow** [comment]
And what about tempco? [These](https://datasheets.maximintegrated.com/en/ds/MAX5898.pdfl) Maxim DACs are low cost and offer 1LSB DNL but would be their  110ppm gain tempo be real killer?

**Comment by hartytp** [comment]
> would be their 110ppm gain tempo be real killer?

The primary application for this design is closed-loop, so temp co is irrelevant.

A low temp co can be nice for other secondary uses (e.g. a generic DAC+ADC+FPGA design), but I wouldn't want to compromise the design's main goals over that, so if there are no comparable DACs with low temp co then it's not an issue.

**Comment by gkasprow** [comment]
The decision is to either use high-end and expensive LTC2000 or one of low-cost DACs

**Comment by hartytp** [comment]
@gkasprow My gut feeling is that we should go for the low-cost DAC.

Before making the final call, @zdun8 could you post a table that compares, the LTC2000, MAX chip, AD9783 (NIST servo) and anything else you think is interesting. Include all the interesting things like cost, power consumption, temp co, INL/DNL, noise, etc, etc. I assume this will be good material for your thesis anyway.

**Comment by zdun8** [comment]
I have updated the spreadsheet with the information about some DACs that I've found. 
@gkasprow do you have MAX5898 in mind? In general it seems, that it could do the job if we turn off the interpolation, then the delay is small, and SFDR is very good. One limitation is that the input data is interleaved (for Q and I outputs), but with 500 MSPS I think we are fine. 

I think LTC2000 is very expensive and has only one channel. Comparing AD9783 and MAX5898 they present similar performance. MAX has lower INL and DNL, but it has higher latency approx. 48 ns comparing to 16 ns of the AD for 500 MHz DAC clock. MAX is cheaper 27 USD vs 43 USD. Please check if my analysis is correct, I could only find that AD9783 latency is 7 cycles in the datasheet. 

https://docs.google.com/spreadsheets/d/1j0nTGpnnnBx4UXwtZlGYXvdnvVj7PuF5h2WQjEc7hA4/edit?usp=sharing

**Comment by gkasprow** [comment]
We do not need 500MS/s but max 125MS/s.  AD9783 has +/2bit DNL which makes it actually 14bit DAC

**Comment by hartytp** [comment]
What's our latency budget?

**Comment by gkasprow** [comment]
I was targeting 100ns,
We are anyway limited by analog BW and setting time.

**Comment by hartytp** [comment]
> I was targeting 100ns,

For the DAC, or for the whole thing?

> I have updated the spreadsheet with the information about some DACs that I've found.

I think you can write off the AD9125 due to unacceptable latency.

> AD9783 has +/2bit DNL which makes it actually 14bit DAC

That's probably okay for this application. More resolutionis nice but non-critical.

**Comment by gkasprow** [comment]
I meant 100ns or so, for entire chain

**Comment by zdun8** [comment]
Then we don't have a lot of timing budget. From the DACs that I've analysed AD9783 has the smallest latency (7 cycles). It's been also used in NIST servo. Another option would be MAX5878.

**Comment by hartytp** [comment]
> I meant 100ns or so, for entire chain

That doesn't leave a lot for the DAC...I guess we can clock the DAC at a higher rate (but only changing the value every few samples). This feels sufficiently tight that we need a full system model before finalizing this choice. But, I suspect we can rule out anything that's more than, say 10 cycles of latency. At that point the list starts to look rather short...

**Comment by gkasprow** [comment]
It does not have to be just 100ns, 150 or even 200ns would be probably fine. THe FPGA also needs a few clock cycles to do even simple algorithm.

**Comment by hartytp** [comment]
Sure, I agree we can spare an extre 1-2 clock cycles in the DAC, but a latency of, say, 20 cycles is probably not going to cut it (unless we run the DACs at a very high clock speed). So worth reducing our options to only cover cases with an acceptable latency.

As this is also a critical parameter, I think we'll need a full system model sooner rather than later.

**Comment by hartytp** [comment]
> I guess we can clock the DAC at a higher rate (but only changing the value every few samples).

Actually, I suppose that doesn't help. To reach higher sample rates, I suspect we'd need a SERDES in the FPGA which would add additional latency. So, without doing a full simulation including FPGA code that meets timing, I'm not sure we can assume a DAC clock rate above 125MHz...

**Comment by dhslichter** [comment]
One option to consider is the AD9117, which we are testing out as a Shuttler candidate DAC.  It runs at 125 MSPS with 4 cycles of latency (32 ns), two channels, 14 bits, <0.5 LSB DNL/INL, relatively low power, low cost.

**Comment by zdun8** [comment]
@gkasprow Would 14 bit DAC be sufficient for Fast Servo? Initial requirement was to use at least 16 bit DAC.

**Comment by zdun8** [comment]
After discussion with @gkasprow we decided that AD9117 is a valid option for Fast Servo. 
It has 4 cycles of delay at 125 MSPS and provides an autocalibration mechanism that lowers the INL and DNL to +/- 0.6 LSB. @hartytp what do you think about this DAC?

**Comment by hartytp** [comment]
That looks ok. What's the preference for this v AD9783? I don't feel strongly, just curious....

**Comment by gkasprow** [comment]
It has longer latency, with low cost FPGA one won't be able to drive it with 500MHz anyway, DNL of +/- 2 LSB makes it essentially 14bit DAC, +/-4LSB makes it 13-bit precise

**Comment by hartytp** [comment]
Fair enough. I haven't checked the specs in detail but assuming the DC performance, noise, stability, etc of the AD9117  look good then go for it!

**Comment by dhslichter** [comment]
FWIW we are currently testing AD9117 to verify datasheet performance and look for any other "gotcha"s.  On the list include DC stability, noise, ability to dither to achieve higher effective bits at DC, measuring tempco, etc.  This will all get put into the Shuttler repository once tests are done.  So far, haven't run across anything that would preclude its use here, especially since the fact that it's part of a closed loop will address slow drifts and tempco.  Definitely monotonic at 14 bits, including major carries, but you have to run the autocalibration routine to get this performance (very simple, no external components required).

**Comment by zdun8** [comment]
@gkasprow is programmable gain needed for DAC AFE also?

**Comment by gkasprow** [comment]
I don't think so

**Comment by zdun8** [comment]
Ok
