### ISSUE TITLE
[sch review] IC10 connect PG 

### ISSUE THREAD

**Issue by filipswit** [sinara-hw/Fast_Servo#22]
Connect PG via 560R to PVIN
![image](https://user-images.githubusercontent.com/24258965/101988452-fa2f5180-3c99-11eb-8796-155f7b62a217.png)

**Comment by zdun8** [comment]
This resistor is optional and PG is not used for this DC/DC converter. 
![image](https://user-images.githubusercontent.com/5497039/102936538-a21df980-44a8-11eb-90ed-67b79f932bee.png)

**Comment by filipswit** [comment]
You are right, I based on table.
