### ISSUE TITLE
[pcb review] U9 move input capacitor

### ISSUE THREAD

**Issue by filipswit** [sinara-hw/Fast_Servo#27]
DS: `Place the CIN capacitor as close as possible to the VIN
and GND connection of the LTM8029.`

![image](https://user-images.githubusercontent.com/24258965/102019119-cfb0c780-3d71-11eb-8e61-0e78f2972ae1.png)

**Comment by gkasprow** [comment]
right, the Cin should be connected to N5V5, not GND to close the AC loop
