### ISSUE TITLE
[pcb review] Input capacitors placement

### ISSUE THREAD

**Issue by filipswit** [sinara-hw/Fast_Servo#30]
DS: `The input capacitor needs to be placed as close as possible to the IC pins`
Looks like here is place for these caps.
![image](https://user-images.githubusercontent.com/24258965/102019817-e0633c80-3d75-11eb-8b84-f1520757abb0.png)

**Comment by zdun8** [comment]
Moved 100nF input capacitor closer to the input pins, thanks.
