### ISSUE TITLE
[pcb review] unmask vias from both sides on thermal pads

### ISSUE THREAD

**Issue by filipswit** [sinara-hw/Fast_Servo#34]

**Comment by zdun8** [comment]
For what reason?

**Comment by filipswit** [comment]
There is a danger of mask pocket.

**Comment by zdun8** [comment]
Brandner or other manufacturers has never complained to me regarding this, but we can change it to avoid this problem.

**Comment by gkasprow** [comment]
Actually, Brandner often complains about it:)
