### ISSUE TITLE
[pcb review] iregular pad shape

### ISSUE THREAD

**Issue by filipswit** [sinara-hw/Fast_Servo#36]
Why one of pads is different?

![image](https://user-images.githubusercontent.com/24258965/102022004-36d77780-3d84-11eb-96b1-700617fd4f56.png)

**Comment by zdun8** [comment]
To be honest I don't know, I copied the placement of the PoE Module from Stabilizer. Maybe @gkasprow  knows why it was done like this in that project.

**Comment by gkasprow** [comment]
It's such to increase the clearance between primary and secondary side
