### ISSUE TITLE
[pcb review] Overlay modifications

### ISSUE THREAD

**Issue by filipswit** [sinara-hw/Fast_Servo#40]
- [ ] Please use one direction of texts.

![image](https://user-images.githubusercontent.com/24258965/102022368-b403ec00-3d86-11eb-8d39-f0a74a9be50b.png)
![image](https://user-images.githubusercontent.com/24258965/102022444-25dc3580-3d87-11eb-908d-61d70c64943d.png)

- [ ] Move text

![image](https://user-images.githubusercontent.com/24258965/102022376-c2520800-3d86-11eb-8044-a76f04d3bc9b.png)
![image](https://user-images.githubusercontent.com/24258965/102022409-f4636a00-3d86-11eb-9c37-250201aba436.png)

- [ ] Rotate

![image](https://user-images.githubusercontent.com/24258965/102022427-09d89400-3d87-11eb-8f39-dd832cd971a0.png)

- [ ] Add connectors description on top overlay

**Comment by zdun8** [comment]
Fixed.
