### ISSUE TITLE
[pcb review] L4 polygon changes

### ISSUE THREAD

**Issue by filipswit** [sinara-hw/Fast_Servo#41]
- [ ] You can move tracks to connect this two polygons

![image](https://user-images.githubusercontent.com/24258965/102022943-54a7db00-3d8a-11eb-8369-b918d9af5fde.png)

- [ ] Remove these antennas

![image](https://user-images.githubusercontent.com/24258965/102022960-76a15d80-3d8a-11eb-8bc8-fb631fa5771c.png)

**Comment by zdun8** [comment]
Fixed. BTW grounded nets will not behave as antennas.

**Comment by gkasprow** [comment]
Actually, they can :)
They became resonators.
