### ISSUE TITLE
[pcb review] Modify ground connection

### ISSUE THREAD

**Issue by filipswit** [sinara-hw/Fast_Servo#43]
C125 is connected to GND with just one 0.254mm path, left side is unconnected, maybe add via on the left.
![image](https://user-images.githubusercontent.com/24258965/102135570-78d1ed80-3e58-11eb-96a0-a2f5b628712c.png)

**Comment by zdun8** [comment]
Fixed it in this way. 
![image](https://user-images.githubusercontent.com/5497039/103460382-0a28d700-4d16-11eb-9ff3-5a9f315b0705.png)
