### ISSUE TITLE
[pcb review] Modify connection

### ISSUE THREAD

**Issue by filipswit** [sinara-hw/Fast_Servo#44]
- [ ] Remove the track or modify plygon.

![image](https://user-images.githubusercontent.com/24258965/102135789-c3536a00-3e58-11eb-9fc6-0e9993bf2b3b.png)

- [ ]  Sides vias may not be connected to poly
![image](https://user-images.githubusercontent.com/24258965/102135991-175e4e80-3e59-11eb-91f5-477d99214d7e.png)

**Comment by zdun8** [comment]
Fixed, thanks
