### ISSUE TITLE
[pcb review] Split plane on L2 and L5

### ISSUE THREAD

**Issue by filipswit** [sinara-hw/Fast_Servo#45]
What for is this unconnected copper?

![image](https://user-images.githubusercontent.com/24258965/102137468-2fcf6880-3e5b-11eb-966a-131188fb150c.png)

**Comment by zdun8** [comment]
This is a recommended layout for the SI5340 oscillator. Please have a look on page 47 and 48 https://www.silabs.com/documents/public/reference-manuals/Si5341-40-D-RM.pdf

**Comment by filipswit** [comment]
Sorry I placed to small screenshot. I'm thinking about this.
![image](https://user-images.githubusercontent.com/24258965/103461637-2b8ec080-4d20-11eb-9c44-7657f341c734.png)

**Comment by zdun8** [comment]
That's strange, this is exactly the same cutout as for the oscillator for SI5340, maybe it's a copy paste error or some Altium bug, I will remove this, thanks.
