### ISSUE TITLE
component availability

### ISSUE THREAD

**Issue by gkasprow** [sinara-hw/Fast_Servo#49]
some components are EOL or hard to find and need replacement
SMBJ5V0A -> SMBJ5.0A
EN6347QA -> MPM3840GQV-Z
AG5300 -> AG5412
ACPL-217-500E -> TCMD1000
DSC1001DL5-100.0000 - ~~DSC6101JE1A-000.0000~~ TC-100.000MBD-T
SI5340B-D-GM -> SI5340B or SI5340C
LTC6406IUD#PBF –> LTC6406IMS8E#PBF
SN74LVC1G125DCKT -> 74LVC1G14GW + 74LVC1G125W5-7 to preserve Stabilizer compatibility
EN5311QI ->  ~~FAN5354MPX~~ FAN8060EMPX
LTM8029IY#PBF ->MAX17577ATC+ 
R0603_32R2_0.1%_0.063W_10PPM ->~~30R 0.1% + 2.2R 0.1%~~ 31R6
TPS62175DQC -> FAN8060EMPX

**Comment by filipswit** [comment]
- [ ] EN6347QA -> MPM3840GQV-Z
RAMP capacitor should be between 10pF and 47pF

- [ ] SI5340B-D-GM -> SI5340B or SI5340C
Nothing has changed in description.

- [ ] IC24 FAN8060EMPX
inverted voltage divider

- [ ] TPS56637RPA looks to be hard to get
