### ISSUE TITLE
v1.0 debugging

### ISSUE THREAD

**Issue by gkasprow** [sinara-hw/Fast_Servo#51]
P3V3 is 3.2V instead of 3V3
PoE works
All rails work
Module with ZynQ board consumes 470mA without Silabs chip which still didn't arrive

**Comment by gkasprow** [comment]
JTAG works, but XADC monitor shows 0

**Comment by gkasprow** [comment]
XADC works after loading pre-built image from Trenz

**Comment by jmatyas** [comment]
- Front Panel LEDs work
- Ethernet LEDs work
- LED1, LED2, LED3 works
- Si5340 configuration and programming via I2C successful ( #54 );  Si5340_nRST OK
- Clock_100M from OSC1 works
- UART works

### ADC LTC2195
- [x] SPI communication
- [x] Data path
- [x] DCO path

### DAC AD9117
- [x] SPI communication
- [x] Data Path (signal generation on both channels)

**Comment by jmatyas** [comment]
Ethernet connection established

**Comment by jmatyas** [comment]
ADC AUX AD7266
- [x] SPI communication OK
- [x] input address lines OK
- [x] range and SGL/!DIFF OK
- [x] sampled values OK

DAC AUX AD5722
- [x] SPI communication OK (both read and write)
- [x] BIN line OK
- [x] nCLR line OK
- [x] output values OK

**Comment by jmatyas** [comment]
- microSD card slot and booting OK
- EEM I2C from EEM connector 
  - both LM75 OK
  - EEPROM OK
- GPIO header OK
- LVDS header OK
