### ISSUE TITLE
Schematics draft - review request

### ISSUE THREAD

**Issue by zdun8** [sinara-hw/Fast_Servo#7]
Hello All, 

I would like to ask you to review the schematics of Fast Servo. They are in a draft stage, but from the electrical point of view they are almost complete. 

Thanks in advance!

**Comment by zdun8** [comment]
There is one known issue. The analog clocks for ADC and DAC need to be externally generated by a dedicated IC.

**Comment by dtcallcock** [comment]
Would it be possible to post a pdf?

**Comment by zdun8** [comment]
Sure, but please give me some time. Due to the fact that I need to add a clock IC, the power supply has to be modified.

**Comment by zdun8** [comment]
I have updated the schematics. Attaching a PDF file. As always the schematics are subject to change during the layout :) [
[Fast_Servo_Sch_Draft_V1.PDF](https://github.com/sinara-hw/Fast_Servo/files/5038604/Fast_Servo_Sch_Draft_V1.PDF)
](url)
