### ISSUE TITLE
Component placement review

### ISSUE THREAD

**Issue by zdun8** [sinara-hw/Fast_Servo#8]
Hello, 

I have started working on the layout. Please have a look at the screenshots below showing the component placement. 
![image](https://user-images.githubusercontent.com/5497039/89781827-592a6180-db14-11ea-85f7-0326695d79fd.png)

![image](https://user-images.githubusercontent.com/5497039/89781776-3ef08380-db14-11ea-9d57-a18bdc5fea0e.png)

**Comment by dtcallcock** [comment]
Is matching the Stabilizer header placement to allow compatibility with Stabilizer mezzanines possible/desirable?

**Comment by zdun8** [comment]
I can check if it's possible. Could you send me the step files for the mezzanines? Or the links to the PCB projects?

**Comment by dtcallcock** [comment]
Pounder is an example of such a mezzanine.  Hopefully everything you need is there in the [Pounder repository](https://github.com/sinara-hw/Pounder).

**Comment by gkasprow** [comment]
@zdun8 we keep full mechanical and electrical (logic levels)  compatibility with Stabilizer. It will propagate to mezzanine compatibility as well. The only difference is missing 10V range.

**Comment by zdun8** [comment]
To be honest, I have completely missed that requirement. I'll update the schematics and PCB accordingly.

**Comment by zdun8** [comment]
Please check the updated placement. 
![image](https://user-images.githubusercontent.com/5497039/92817116-86de2100-f3c6-11ea-8cb0-fe9ba6f97ddb.png)
![image](https://user-images.githubusercontent.com/5497039/92817463-e2101380-f3c6-11ea-9b32-ec557c48d876.png)

**Comment by zdun8** [comment]
@gkasprow Yes, local power are only LDOs. 

Basic placement version of the PCB is on the repo.
