### ISSUE TITLE
design review

### ISSUE THREAD

**Issue by gkasprow** [sinara-hw/Fast_Servo#9]
- [x] arrange that all designators and texts do no overlap,  make sure they are not inverted (I know about Altium option)
- [x] please add 0R option resistor that grounds input connectors
- [x] add 0R between U1A and IC12 for debugging
- [x] don't we need ESD protection for SD?
- [x] did U do the power budget? How much power would LDOs dissipate? Please add a suitable note. use ADI tool for power tree simulation.
- [x] was power sequencing implemented? One must make sure that no SOM signals are present before SOM is supplied
- [x] please mark which banks are 3.3 and 1.8V rated
- [x] why we need both R23 and R6?
- [x] rename P1V0 -> REF1V0
- [x] add 0R to J8 - L2, L4, just in case
- [x] make sure EEM LVDS0 goes to Clock Capable pins and 2V5 bank. We plan to use Artix/Kintex/Zynq devices, make sure such a bank works with LVDS. LVDS requires 1V8 for HP banks and 2V5 for HR banks.
- [x] specify which Trenz modules can be used. Take into account the signalling standard and modules based on Artix, Kintex7 and Zynq.

**Comment by zdun8** [comment]
Thanks for the review. I will introduce the changes and will let you know if I have any doubts.

**Comment by zdun8** [comment]
> * don't we need ESD protection for SD?
There is a voltage level translator between the SD-Card and SoM, so additional ESD protection is not needed.

> * specify which Trenz modules can be used. Take into account the signalling standard and modules based on Artix, Kintex7 and Zynq

For now, we can support TE0712 (Artix), TE0715-15 (Zynq Artix), TE0715-30 (Zynq Kitex), TE7020 (Zynq Artix), is that okay? @gkasprow 

> * did U do the power budget? How much power would LDOs dissipate? Please add a suitable note. use ADI tool for power tree simulation
![image](https://user-images.githubusercontent.com/5497039/91744442-d13af300-ebb9-11ea-8c18-ff94ed5b444e.png)

**Comment by gkasprow** [comment]
are you sure the level converter has ESD protection?
Support for these modules is fine, just place an info on schematics

**Comment by zdun8** [comment]
> are you sure the level converter has ESD protection?

Yes, is that enough? 
![image](https://user-images.githubusercontent.com/5497039/91911308-14c45880-ecb1-11ea-98d8-3f08b68c8bf7.png)

**Comment by gkasprow** [comment]
ok, should be fine.

**Comment by zdun8** [comment]
Routed PCB is ready for review on the repo. Please let me know if you find anything! 
 
I have checked the pinout in vivado for template projects for TE0720, TE0715-15 and TE0715-30 and the bitstream is properly generated. Archived projects are also available on the repo.
